enum ActionTypes {
  FETCH_USER_GISTS = "FETCH_USER_GISTS",
  FETCH_USER_GISTS_SUCCESS = "FETCH_USER_GISTS_SUCCESS",
  FETCH_USER_GISTS_FAILED = "FETCH_USER_GISTS_FAILED",
}

export default ActionTypes;
