enum ActionTypes {
  VALIDATE_USERNAME = "VALIDATE_USERNAME",
  VALIDATE_USERNAME_SUCCESS = "VALIDATE_USERNAME_SUCCESS",
  VALIDATE_USERNAME_FAILED = "VALIDATE_USERNAME_FAILED",
}

export default ActionTypes;
